-- MySQL Script generated by MySQL Workbench
-- 05/02/15 19:05:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farolDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farolDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farolDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `farolDB` ;

-- -----------------------------------------------------
-- Table `farolDB`.`tbMateria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farolDB`.`tbMateria` ;

CREATE TABLE IF NOT EXISTS `farolDB`.`tbMateria` (
  `codigo` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farolDB`.`tbProfessor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farolDB`.`tbProfessor` ;

CREATE TABLE IF NOT EXISTS `farolDB`.`tbProfessor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farolDB`.`tbUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farolDB`.`tbUsuario` ;

CREATE TABLE IF NOT EXISTS `farolDB`.`tbUsuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `admin` TINYINT(1) NOT NULL,
  `moderador` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farolDB`.`tbProvaTrabalho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `farolDB`.`tbProvaTrabalho` ;

CREATE TABLE IF NOT EXISTS `farolDB`.`tbProvaTrabalho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `provaTrabalho` ENUM('prova', 'trabalho') NOT NULL,
  `numero` ENUM('1', '2', '3', 'final') NULL,
  `substitutiva` TINYINT(1) NULL,
  `arquivo` VARCHAR(255) NOT NULL,
  `status` ENUM('pendente','aprovado') NOT NULL,
  `imagem` TINYINT(1) NOT NULL,
  `ano` INT NULL,
  `semestre` INT NULL,
  `tbMateria_codigo` VARCHAR(10) NOT NULL,
  `tbProfessor_id` INT NOT NULL,
  `tbUsuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `arquivo_UNIQUE` (`arquivo` ASC),
  INDEX `fk_tbProvaTrabalho_tbMateria_idx` (`tbMateria_codigo` ASC),
  INDEX `fk_tbProvaTrabalho_tbProfessor1_idx` (`tbProfessor_id` ASC),
  INDEX `fk_tbProvaTrabalho_tbUsuario1_idx` (`tbUsuario_id` ASC),
  CONSTRAINT `fk_tbProvaTrabalho_tbMateria`
    FOREIGN KEY (`tbMateria_codigo`)
    REFERENCES `farolDB`.`tbMateria` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProvaTrabalho_tbProfessor1`
    FOREIGN KEY (`tbProfessor_id`)
    REFERENCES `farolDB`.`tbProfessor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbProvaTrabalho_tbUsuario1`
    FOREIGN KEY (`tbUsuario_id`)
    REFERENCES `farolDB`.`tbUsuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- INSERTS das matérias (apenas a grade obrigatória 2011 BCC e IBM)
INSERT INTO tbMateria values('CI068','Circuitos Lógicos');
INSERT INTO tbMateria values('CI055','Algoritmos e Estruturas de Dados');
INSERT INTO tbMateria values('CM046','Introdução à Álgebra');
INSERT INTO tbMateria values('CM045','Geometria Analítica');
INSERT INTO tbMateria values('CM201','Cálculo Diferencial e Integral I');
INSERT INTO tbMateria values('CI210','Processos Digitais e Microprocessadores');
INSERT INTO tbMateria values('CI056','Algoritmos e Estruturas de Dados II');
INSERT INTO tbMateria values('CI067','Oficina de Computação');
INSERT INTO tbMateria values('CM005','Álgebra Linear');
INSERT INTO tbMateria values('CM202','Cálculo Diferencial e Integral II');
INSERT INTO tbMateria values('CI212','Organização e Arquitetura de Computadores');
INSERT INTO tbMateria values('CI057','Algoritmos e Estruturas de Dados III');
INSERT INTO tbMateria values('CI237','Matemática Discreta');
INSERT INTO tbMateria values('CI166','Metodologia Científica');
INSERT INTO tbMateria values('CI064','Software Básico');
INSERT INTO tbMateria values('CI215','Sistemas Operacionais');
INSERT INTO tbMateria values('CI062','Técnicas Alternativas de Programação');
INSERT INTO tbMateria values('CE003','Estatística II');
INSERT INTO tbMateria values('CI058','Redes de Computadores I');
INSERT INTO tbMateria values('CI164','Introdução a Computação Científica');
INSERT INTO tbMateria values('CI162','Engenharia de Requisitos');
INSERT INTO tbMateria values('CI065','Algoritmos e Teoria dos Grafos');
INSERT INTO tbMateria values('CI059','Introdução a Teoria da Computação');
INSERT INTO tbMateria values('CI061','Redes de Computadores II');
INSERT INTO tbMateria values('SA214','Introdução a Teoria Geral da Administração');
INSERT INTO tbMateria values('CI163','Projeto de Software');
INSERT INTO tbMateria values('CI165','Análise de Algoritmos');
INSERT INTO tbMateria values('CI209','Inteligência Artificial');
INSERT INTO tbMateria values('CI218','Sistemas de Bancos de Dados');
INSERT INTO tbMateria values('CI220','Sistemas Teoria de Sistemas');
INSERT INTO tbMateria values('CI221','Enegenharia de Software');
INSERT INTO tbMateria values('CI211','Construção de Compiladores');
INSERT INTO tbMateria values('CI241','Introdução a Sistemas Computacionais');
INSERT INTO tbMateria values('BA040','Anatomia Humana Sistêmica');
INSERT INTO tbMateria values('CI243','Fundamentos de Projeto e Arquitetura de Computadores');
INSERT INTO tbMateria values('BQ005','Introdução a Bioquímica');
INSERT INTO tbMateria values('CI244','Fundamentos de Redes e Sistemas Distribuídos');
INSERT INTO tbMateria values('BQ054','Biologia Molecular e Bioinformática');
INSERT INTO tbMateria values('BC056','Fundamentos de Biologica Celular e Tecidual');
INSERT INTO tbMateria values('BG054','Genética e Evolução para o Curso de Informática Biomédica');
INSERT INTO tbMateria values('BF075','Fisiologia para Informática Biomédica');
INSERT INTO tbMateria values('CI394','Processamento de Imagens');
INSERT INTO tbMateria values('CI316','Programação Paralela');
INSERT INTO tbMateria values('MN127','Saúde, Meio Ambiente e Sociedade');
INSERT INTO tbMateria values('CI167','Sistemas de Informação em Saúda');
INSERT INTO tbMateria values('CI171','Aprendizado de Máquina');
INSERT INTO tbMateria values('MN128','Organização do Sistema de Saúde Brasileiro');
INSERT INTO tbMateria values('CI169','Bioinformática');
INSERT INTO tbMateria values('CI172','Processamento de Imagens Biomédicas');
INSERT INTO tbMateria values('MN129','Metodologia da Pesquisa e Bioética em Saúde');
INSERT INTO tbMateria values('CI262','Trabalho de Conclusão de Curso em Informática Biomédica');

-- INSERTS dos professores
INSERT INTO tbProfessor (nome) VALUES ('Aldri Luiz dos Santos');
INSERT INTO tbProfessor (nome) VALUES ('Alexandre Ibrahim Direne');
INSERT INTO tbProfessor (nome) VALUES ('André Luís Vignatti');
INSERT INTO tbProfessor (nome) VALUES ('André Luiz Pires Guedes');
INSERT INTO tbProfessor (nome) VALUES ('Andrey Ricardo Pimentel');
INSERT INTO tbProfessor (nome) VALUES ('Andrey Ricardo Pimentel');
INSERT INTO tbProfessor (nome) VALUES ('Antônio Edison Urban');
INSERT INTO tbProfessor (nome) VALUES ('Armando Luiz Nicolini Delgado');
INSERT INTO tbProfessor (nome) VALUES ('Aurora Trindad Ramirez Pozo');
INSERT INTO tbProfessor (nome) VALUES ('Bruno Müller Júnior');
INSERT INTO tbProfessor (nome) VALUES ('Carmem Satie Hara');
INSERT INTO tbProfessor (nome) VALUES ('Daniel Weingaertner');
INSERT INTO tbProfessor (nome) VALUES ('Eduardo Cunha de Almeida');
INSERT INTO tbProfessor (nome) VALUES ('Eduardo Cunha de Almeida');
INSERT INTO tbProfessor (nome) VALUES ('Eduardo Jaques Spinosa');
INSERT INTO tbProfessor (nome) VALUES ('Eduardo Todt');
INSERT INTO tbProfessor (nome) VALUES ('Elenice Mara Matos Novak');
INSERT INTO tbProfessor (nome) VALUES ('Elias Procópio Duarte Júnior');
INSERT INTO tbProfessor (nome) VALUES ('Fabiano Silva');
INSERT INTO tbProfessor (nome) VALUES ('Laura Sánchez García');
INSERT INTO tbProfessor (nome) VALUES ('Leôncio Saraiva Madruga');
INSERT INTO tbProfessor (nome) VALUES ('Leticia Mara Peres');
INSERT INTO tbProfessor (nome) VALUES ('Lucas Ferrari de Oliveira');
INSERT INTO tbProfessor (nome) VALUES ('Luciano Silva');
INSERT INTO tbProfessor (nome) VALUES ('Luis Allan Kunzle');
INSERT INTO tbProfessor (nome) VALUES ('Luis Carlos Erpen de Bona');
INSERT INTO tbProfessor (nome) VALUES ('Luiz Carlos Pessoa Albini');
INSERT INTO tbProfessor (nome) VALUES ('Luiz Eduardo Soares de Oliveira');
INSERT INTO tbProfessor (nome) VALUES ('Marcos Alexandre Castilho');
INSERT INTO tbProfessor (nome) VALUES ('Marcos Didonet Del Fabro');
INSERT INTO tbProfessor (nome) VALUES ('Marcos Sfair Sunye');
INSERT INTO tbProfessor (nome) VALUES ('Michele Nogueira Lima');
INSERT INTO tbProfessor (nome) VALUES ('Olga Regina Pereira Bellon');
INSERT INTO tbProfessor (nome) VALUES ('Paulo Eliseu Portella');
INSERT INTO tbProfessor (nome) VALUES ('Renato Carmo');
INSERT INTO tbProfessor (nome) VALUES ('Roberto André Hexsel');
INSERT INTO tbProfessor (nome) VALUES ('Roberto de Fino Bentes');
INSERT INTO tbProfessor (nome) VALUES ('Setembrino Soares Ferreira Jr.');
INSERT INTO tbProfessor (nome) VALUES ('Silvia Regina Vergilio');
INSERT INTO tbProfessor (nome) VALUES ('Wagner Machado Nunan Zola');